language:
- python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: YcWmKo2/0GnflL+PxfUTbwvoa6uInL+KNI9/rSa9jGpGoHqhQ+hyWRTt5a7vn/353rWID+Uf8xFrjBEuIrrROO3fOngQfi4kRJXN5hovpu6IY7aQtHKqk0+LKMzoCM953KrWrOqSp8EqbYZNMRpbQHXA/Tfh80dk7rmaWI97RUmJ7POf7rR031i0ZRK66eRKAIRSSSiTaDXldqHD6kxyx8xoaaonZZqXkqmWHIe1aAaCF0uwQ7jWmLXi9StGFhnYOIPnYUMN0nkt5CB57RH4IXWaLunfKfNg9z+TQ87ruZhOnQp8yRYE2rgjje1mH7Gb2tcwuhuXrFUG9DuTYCNoRwrxkymHjSmxEmEhka9WIpIX6vYuMWS/dyShTsvpUM/9bhgki8bsuXE+Wnef9mrCiPDSWs1ygFoj0jvcE+6oa1dpePlGB/m3a92Ban59ShV9uP/t48AtFvd0sAfR44+GUxmhQPHQzGhVjs/QKx13DZXvVuTg01KmqnFuzYIUgvWwCvwlkuhmf7QOkiKT+z0YMfJ25vTl9QLkcNJvTQugWTVzO11PKvb/5c4AUJlG8cvv1NraLp232JH1eiitFM3ervouGUZ+9Hwx01im6bkv5kxmd7nUoQPHNQS8vbIW+Sgak5pn5MB6aMl2G+POpfd+Dq7SAzsPsiyW6D7GhD2NwCY=
  app: flasktaskr-2019
  on:
    repo: e-larm/flasktaskr
